require("zone.js/dist/zone-node"); // todo: why?

import * as functions from "firebase-functions";
import { enableProdMode } from "@angular/core";
const { app } = require("../server.js"); //keep it as require(), not `import` to prevent overriding the file `dist/server.js` that generated by angular

enableProdMode();

// to test: https://us-central1-<projectId>.cloudfunctions.net/<functionName>
// or http://localhost:4201/<projectId>/us-central1/<functionName>
//get projectId from the file: `/.firebaserc`
export const test = functions.https.onRequest((request, response) => {
  response.send("firebase function works");
});

export const ssr = functions.https.onRequest(app);
